#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "SpaceVim"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = 'myspacevim#before'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
auto_completion_enable_snippets_in_popup = false

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
enable = false

[[layers]]
name = "checkers"

[[layers]]
name = "colorscheme"

[[layers]]
name = "default"

[[layers]]
name = "git"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#extra"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#sh"

[[layers]]
name = "sudo"

[[layers]]
name = "core#statusline"

[[layers]]
name = "lang#xml"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#graphql"

[[layers]]
name = "lang#ipynb"

[[layers]]
name = "lang#ruby"

[[layers]]
name = "lsp"
enabled_clients = ['pyright']

[[layers]]
name = "VersionControl"

[[custom_plugins]]
repo = 'pearofducks/ansible-vim'
